function esc(s) {
  const d = document.createElement('div');
  d.textContent = s;
  return d.innerHTML;
}
const FEMALE_NAMES = new Set([
  // --- English / American ---
  'abby','abigail','ada','adele','adeline','adriana','adrienne','agnes','aileen','aimee',
  'ainsley','alana','alejandra','alessandra','alexa','alexandra','alexis','alice','alicia',
  'alina','alison','allison','alma','alyssa','amanda','amber','amelia','amy','ana',
  'anastasia','andrea','angela','angelica','angelina','angie','anita','ann','anna',
  'annabelle','anne','annette','annie','april','ariana','arianna','ariel','arlene',
  'ashley','astrid','athena','aubrey','audrey','aurora','autumn','ava','avery',
  'bailey','barbara','beatrice','becky','belinda','bella','bernadette','bernice','bertha',
  'bessie','beth','bethany','betsy','betty','beverly','bianca','billie','blair','blanche',
  'bonnie','brandi','brandy','breanna','brenda','bridget','brittany','brittney','brooke',
  'brooklyn','brynn',
  'caitlin','caitlyn','callie','camila','camille','candace','candice','cara','carey',
  'carina','carla','carly','carmen','carol','carolina','caroline','carolyn','carrie',
  'casey','cassandra','cassidy','cassie','catalina','catherine','cecilia','celeste','celia',
  'chandra','charity','charlene','charlotte','charmaine','chelsea','cheri','cheryl','chloe',
  'christa','christina','christine','ciara','cindy','claire','clara','clarissa','claudia',
  'clementine','colette','colleen','connie','constance','cora','coral','cordelia','corinne',
  'cornelia','courtney','crystal','cynthia',
  'dahlia','daisy','dakota','dana','daniela','daniella','danielle','daphne','darcy',
  'darlene','dawn','deanna','debbie','deborah','debra','dee','deidre','delia','delilah',
  'della','delores','dena','denise','desiree','destiny','devon','diana','diane','dianne',
  'dina','dixie','dolores','dominique','donna','dora','doreen','doris','dorothy','dottie',
  'eileen','elaine','eleanor','elena','eliana','elisa','elisabeth','elise','eliza',
  'elizabeth','ella','ellen','ellie','eloise','elsa','elsie','ember','emery','emilia',
  'emily','emma','emmeline','enid','erica','erika','erin','ernestine','esmeralda',
  'esperanza','estelle','esther','ethel','etta','eugenia','eunice','eva','evangeline',
  'eve','evelyn','everleigh',
  'faith','fallon','fanny','farrah','fatima','fawn','faye','felicia','felicity','fern',
  'fernanda','fiona','flora','florence','francesca','frances','francine','freda','freya',
  'frida',
  'gabriela','gabriella','gabrielle','gail','galilea','gemma','genevieve','georgia',
  'georgina','geraldine','gertrude','gia','gillian','gina','ginger','giselle','gladys',
  'glenda','gloria','goldie','grace','gracie','greta','gretchen','griselda','guadalupe',
  'gwen','gwendolyn',
  'hadley','hailey','haley','hallie','hanna','hannah','harley','harmony','harriet',
  'hattie','hayden','hayley','hazel','heather','heidi','helen','helena','helene','henrietta',
  'hilary','hilda','hillary','holly','honey','hope',
  'ida','ilene','imani','imelda','imogen','ina','ines','ingrid','iona','irene','iris',
  'irma','isabel','isabella','isabelle','isla','itzel','ivy','izabella',
  'jackie','jacqueline','jacquelyn','jade','jada','jamie','jan','jane','janelle','janet',
  'janice','janine','jasmine','jayla','jean','jeanette','jeanine','jeanne','jeannette',
  'jemma','jenna','jennifer','jenny','jessica','jessie','jewel','jill','jillian','joan',
  'joann','joanna','joanne','jocelyn','jodi','jodie','johanna','jolene','joni','jordan',
  'josephine','josie','joy','joyce','juana','juanita','judith','judy','julia','juliana',
  'julianne','julie','juliet','juliette','june','justine',
  'kailey','kaitlin','kaitlyn','kali','kamila','kara','karen','kari','karina','karla',
  'kate','katelyn','katerina','katherine','kathleen','kathryn','kathy','katie','katrina',
  'kay','kaya','kayla','kaylee','kaylin','keely','keira','kelley','kelli','kelly','kelsey',
  'kendra','kennedy','kerry','kiana','kiara','kim','kimberly','kira','kirsten','kitty',
  'krista','kristen','kristin','kristina','kristine','krystal','kyla','kylie','kyra',
  'lacey','laila','lainey','lana','lara','larissa','laura','laurel','lauren','laurie',
  'laverne','layla','lea','leah','leanne','leia','leigh','leila','leilani','lena','lenora',
  'leona','leslie','leticia','lexi','lia','liana','libby','lila','lillian','lillie',
  'lilly','lily','lina','linda','lindsay','lindsey','lisa','liv','livia','liz','liza',
  'lizzie','logan','lois','lola','london','lorelei','lorena','loretta','lori','lorraine',
  'lottie','louisa','louise','lucia','luciana','lucille','lucinda','lucy','luella','luisa',
  'luna','lupe','luz','lydia','lynda','lynn','lynnette',
  'mabel','macy','maddison','madeleine','madeline','madelyn','madison','mae','magdalena',
  'maggie','maia','maisie','makayla','makenna','malika','mallory','mamie','mandy','mara',
  'marcella','marcia','margaret','margie','margo','margot','marguerite','maria','mariah',
  'marian','mariana','marianne','maribel','marie','mariela','marilyn','marina','marisa',
  'marisol','marissa','marjorie','marla','marlene','marsha','marta','martha','mary',
  'maryann','matilda','mattie','maude','maura','maureen','mavis','maxine','maya','mckenna',
  'mckenzie','meagan','megan','meghan','melanie','melinda','melissa','melody','mercedes',
  'meredith','mia','michaela','michele','michelle','mikaela','mikayla','mila','mildred',
  'millie','mimi','mindy','minerva','miranda','miriam','misty','mitzi','moira','molly',
  'monica','monique','morgan','muriel','mya','myra','myrna','myrtle',
  'nadia','nadine','nancy','nanette','naomi','natalia','natalie','natasha','nayeli',
  'nelda','nellie','nettie','neve','nia','nichole','nicole','nina','noelle','nola','nora',
  'noreen','norah','norma','nova','nyla',
  'octavia','odette','olga','olive','olivia','opal','ophelia','ora',
  'paige','paloma','pam','pamela','pandora','paola','paris','patience','patricia','patsy',
  'patti','patty','paula','paulette','paulina','pauline','pearl','peggy','penelope','penny',
  'perla','petra','peyton','phoebe','phyllis','piper','polly','poppy','portia','precious',
  'priscilla','prudence',
  'quinn',
  'rachael','rachel','ramona','raven','raquel','reba','rebecca','reese','regan','regina',
  'rena','renata','renee','reyna','rhea','rhiannon','rhonda','riley','rita','rivka',
  'roberta','robin','rochelle','rocio','roma','rosa','rosalie','rosalind','rosalyn',
  'rosanna','rose','roseann','rosemarie','rosemary','rosetta','rosie','rowan','roxana',
  'roxanne','ruby','ruth','rylee',
  'sabina','sabrina','sadie','sage','sallie','sally','salma','samantha','sandra','sandy',
  'sara','sarah','sasha','savanna','savannah','scarlett','selena','selma','serena','shana',
  'shaniqua','shanna','shannon','shari','sharon','shauna','shawna','shayla','sheena',
  'sheila','shelby','shelley','shelly','sheri','sherri','sherry','sheryl','shirley',
  'sienna','sierra','sigrid','silvana','silvia','simone','siobhan','skye','skylar','sloane',
  'socorro','sofia','solange','soledad','sondra','sonia','sonya','sophia','sophie','stacey',
  'stacy','starla','stella','stephanie','stormy','sue','summer','sunny','suri','susan',
  'susana','susanne','susie','suzanne','suzette','sybil','sydney','sylvia',
  'tabitha','talia','tallulah','tamara','tami','tamika','tammy','tania','tanisha','tanya',
  'tara','taryn','tatiana','tatum','taylor','tegan','teresa','teri','terri','terry','tess',
  'tessa','thalia','thelma','theodora','theresa','tia','tiana','tiara','tierra','tiffany',
  'tilda','tina','toni','tonya','tori','tracey','traci','tracy','tricia','trina','trisha',
  'trudy',
  'uma','ursula',
  'valentina','valeria','valerie','vanessa','veda','velma','venus','vera','veronica',
  'vicki','vickie','vicky','victoria','viola','violet','virginia','vivian','viviana',
  'vivienne',
  'wanda','waverly','wendy','whitney','willa','willow','wilma','winifred','winnie','wynne',
  'ximena','xiomara',
  'yadira','yamileth','yasmin','yasmine','yesenia','yolanda','yvette','yvonne',
  'zara','zelda','zella','zena','zia','zinnia','zoe','zoey','zola','zora','zuri',

  // --- Spanish / Latin American ---
  'adelita','adoracion','agustina','aida','aitana','alondra','amada','amparo','araceli',
  'ariadna','azucena','beatriz','belen','blanca','camila','caridad','carlota','cayetana',
  'celia','charo','cielo','citlali','clara','clarisa','clotilde','concepcion','consuelo',
  'corazon','cristina','cruz','dalia','daniela','dolores','dulce','edith','elena','elisa',
  'eloisa','elvira','emilia','encarnacion','enriqueta','estefania','estrella','eugenia',
  'fatima','flor','gabriela','genoveva','graciela','ines','inmaculada','irene','isabel',
  'isidora','ivonne','jimena','josefa','josefina','juana','leonor','lourdes','lucero',
  'lucia','luisa','lupe','luz','magdalena','maite','manuela','marcela','margarita',
  'marisela','marta','mercedes','milagros','mirta','montserrat','natividad','nerea',
  'nieves','nuria','ofelia','paloma','piedad','pilar','rafaela','ramona','raquel',
  'rebeca','remedios','rocio','rosario','rosaura','rufina','sara','socorro','soledad',
  'sonia','soraya','susana','teresa','valentina','valeria','veronika','victoria',
  'virginia','xiomara','yolanda','zaira','zulema',

  // --- French ---
  'adeline','adele','agathe','albertine','alexandrine','amelie','anais','andree','angele',
  'angelique','anouk','antoinette','ariane','arielle','arlette','aurelie','aurore',
  'babette','bernadette','berthe','brigitte','camille','capucine','carine','cecile',
  'celeste','celine','chantal','charlotte','christelle','christiane','claire','clarisse',
  'clemence','clementine','clothilde','colette','coralie','corinne','cosette','danielle',
  'delphine','denise','desiree','diane','dominique','dorothee','edith','edwige','eglantine',
  'eleonore','elodie','eloise','emeline','emilie','emmanuelle','estelle','eugenie',
  'fabienne','fanny','felicie','flavie','florence','fleur','francine','francoise',
  'frederique','gabrielle','gaelle','genevieve','georgette','germaine','ghislaine',
  'gisele','giselle','helene','henriette','hortense','huguette','irene','isabelle',
  'jacqueline','jeanne','jocelyne','joelle','josee','josette','josiane','juliette',
  'justine','laurence','laure','leonie','lisette','lorraine','luce','lucette','lucienne',
  'lucile','lucie','madeleine','manon','marcelle','margaux','margot','marguerite',
  'marianne','marie','marielle','martine','mathilde','maud','michele','mireille',
  'monique','morgane','muriel','mylene','nadia','nadine','nathalie','nicole','ninon',
  'noelle','noemie','oceane','odette','odile','ophelie','pascale','patricia','paulette',
  'pauline','perrine','philomene','rachelle','raymonde','regine','renee','romane','rosalie',
  'roseline','sabine','sandrine','severine','simone','solange','solene','sophie',
  'stephanie','suzanne','sylviane','sylvie','therese','valentine','valerie','veronique',
  'victoire','virginie','viviane','yvette','yvonne','zoe',

  // --- Italian ---
  'agnese','alessandra','alessia','allegra','amara','ambra','annamaria','annalisa',
  'antonella','arianna','beatrice','benedetta','bianca','brunella','carla','carlotta',
  'carmela','caterina','cecilia','chiara','cinzia','claudia','concetta','cristina',
  'daniela','donatella','eleonora','elena','elisa','elisabetta','emanuela','emilia',
  'enrichetta','enza','fabiana','fabiola','federica','filomena','fiorella','fiamma',
  'flavia','francesca','franca','gabriella','gemma','giada','gilda','giorgia','giovanna',
  'gisella','giulia','giuliana','grazia','graziella','ida','ilaria','iolanda','irene',
  'isabella','lara','laura','letizia','lia','liliana','lorena','lorenza','luana','lucia',
  'luciana','luisa','maddalena','manuela','mara','marcella','margherita','maria',
  'mariangela','mariella','marina','marisa','marta','martina','maura','michela','milena',
  'mirella','monica','nadia','nicoletta','noemi','nunzia','ornella','oriana','paola',
  'patrizia','piera','raffaella','renata','rita','roberta','romana','rosa','rosalia',
  'rosanna','rosetta','rossana','rossella','sabina','sabrina','sandra','sara','serena',
  'silvana','silvia','simona','sonia','stefania','susanna','tania','tatiana','teresa',
  'tiziana','valentina','valeria','vanessa','veronica','viola','virginia','vittoria',

  // --- German / Scandinavian ---
  'adelheid','aleksandra','alva','amelie','anika','anke','anna','annaliese','annegret',
  'anneliese','annika','antje','asta','astrid','barbel','beata','berit','berta','birgit',
  'birgitta','bodil','britta','brunhilde','dagmar','dagny','ebba','edda','elfriede',
  'elina','elke','ellinor','elsa','elvira','emilia','erika','erna','eva','freya','frieda',
  'frida','gerda','gertrud','gisela','greta','gudrun','gunda','hanna','hannelore','hedda',
  'hedvig','heide','heidi','helga','hella','herta','hilde','hildegard','ida','ilse','inga',
  'inge','ingeborg','ingrid','irma','jutta','karin','karla','karolina','katarina',
  'katharina','katja','kerstin','kirsten','klara','kornelia','kristina','liese','liesel',
  'lina','linda','linnea','lisbeth','liselotte','lotta','lovisa','lykke','magda',
  'magdalena','maja','malin','margarete','margit','margot','maria','marianne','marie',
  'marlene','marta','mathilda','meike','mette','mia','michaela','mona','monika','nadia',
  'nanna','nele','nora','oda','olga','petra','pia','renate','romy','ronja','rosa',
  'rosemarie','rut','ruth','saga','sanna','sigrid','silke','silje','siri','solveig',
  'sonja','stefanie','svea','tanja','thea','therese','tilda','tine','tove','trude',
  'ulla','ulrike','ursula','ute','vera','veronika','waltraud','wanda','wiebke','wilma',

  // --- Eastern European / Slavic ---
  'agata','agnieszka','aksana','aleksandra','alena','alina','alla','anastasia','andreja',
  'ania','anja','anna','anzhela','basia','beata','bogdana','bozena','branka','brygida',
  'dagmara','dalia','danica','daniela','daria','darya','diana','dobromila','dominika',
  'dorota','dragana','dusanka','edita','ekaterina','elena','elina','eliska','emilia',
  'eva','ewa','galina','gordana','grazyna','halina','hana','ilona','inga','inessa',
  'irena','irina','iryna','ivana','ivanka','iwona','izabela','jadwiga','jana','janina',
  'jaroslava','jasna','jelena','jitka','jolanta','jovana','julia','julija','justyna',
  'kamila','karolina','kasia','katarina','katerina','katja','klara','klaudia','krystyna',
  'ksenia','kveta','larisa','larysa','lenka','lesia','lidiya','liliya','ljuba',
  'ljubica','ludmila','lyudmila','magdalena','maja','malgorzata','mara','marcela',
  'marika','marina','marta','martina','maryna','maya','michaela','milada','milana',
  'milena','milica','mira','mirjana','miroslava','mirta','monika','nada','nadejda',
  'nadia','nadiya','natalija','natalia','nataliya','natasa','natasha','nela','nevena',
  'nika','nina','nora','oksana','olena','olga','olha','oxana','patrycja','paulina',
  'pavla','pavlina','petra','polina','rada','radka','raina','raisa','renata','roksana',
  'romana','roza','ruslana','ruzena','sabina','sandra','sanja','silvija','simona','slava',
  'slavica','snezhana','sofia','sofiya','sonja','stanislava','stefaniya','stella',
  'svetlana','sylwia','taisiya','tamara','tanya','tatiana','tatyana','tereza','tetiana',
  'valentina','vanda','vanja','varvara','vasylyna','vera','veronika','vesna','viktoriya',
  'violeta','vladimira','vladislava','wanda','yelena','yulia','yuliya','zdenka','zlata',
  'zora','zuzana','zuzanna',

  // --- South Asian ---
  'aadhira','aaradhya','aanya','aarna','aarushi','aditi','ahana','aisha','akshara',
  'amara','amrita','ananya','anika','anjali','anushka','anya','aparna','archana','arya',
  'asha','avani','avni','bhavana','bhavna','chaitra','chandra','charvi','devi','devika',
  'dhanya','dipika','divya','durga','esha','gauri','geeta','gita','gowri','hansa','harini',
  'harsha','hema','indira','isha','ishita','jaya','jayanti','jhanvi','jyoti','jyotsna',
  'kajal','kalpana','kamala','kanta','kavita','kavya','keerthi','kiran','kirti','komal',
  'kriti','lata','latika','lavanya','laxmi','lekha','lila','madhavi','madhu','mahi',
  'malini','mamta','manisha','maya','medha','meena','meera','megha','mira','misha','mohini',
  'mythili','nalini','namita','nandini','navya','neelam','neesha','neeta','neha','nikita',
  'nila','nimra','nisha','nita','nivedita','padma','pallavi','parvati','pooja','poonam',
  'prabha','pragya','prarthana','pratibha','preeti','prerna','priya','priyanka','pushpa',
  'radha','rajani','raji','ramya','rani','rashmi','ratna','reena','rekha','revathi','rima',
  'risha','ritu','riya','rohini','roopa','roshni','rukmini','saarika','sadhana','sahana',
  'sakshi','sandhya','sangita','sanika','saniya','sanjana','saraswati','sarika','saroja',
  'savita','seema','shaila','shakti','shanti','sharmila','sheela','shikha','shilpa',
  'shobha','shreya','shruti','shweta','sita','smita','smriti','sneha','sonali','sonia',
  'sruti','sudha','sujata','sumitra','sunita','supriya','surya','sushma','swapna','swati',
  'tanvi','tara','teja','trisha','tulsi','uma','usha','vaishnavi','vanita','varsha',
  'vasudha','veena','vidya','vimala','vinita','yamuna','yasmin','zara',
  // Pakistani / Bangladeshi
  'abeera','afreen','aliya','amna','anum','ayesha','bushra','farah','fariha','farzana',
  'ghazala','habiba','hina','humaira','humera','iqra','khadija','lubna','mahira','maliha',
  'mariam','mehreen','nabila','nadia','naila','nasreen','nazma','nusrat','rabia','razia',
  'rubina','rukhsana','sadaf','saima','saiqa','samina','sana','shabana','shazia','sidra',
  'sobia','sumaiya','tahira','uzma','yasmeen','zainab','zubaida',

  // --- East Asian ---
  // Chinese (romanized)
  'ai','an','bao','chan','chen','cui','dan','fang','fen','guiying','hong','hua','hui',
  'jia','jiali','jiao','jie','jing','juan','jun','lan','lei','li','lian','lili','lin',
  'ling','liu','mei','meili','meiying','min','ming','na','nan','ning','ping','qi','qian',
  'qing','rong','rui','shan','shu','shuang','ting','wan','wei','wen','xia','xian',
  'xiang','xiao','xiaoli','xiaoming','xin','xing','xiulan','xiuying','xue','ya','yan',
  'yang','ying','yong','yu','yuan','yue','yun','zhen','zhi','zhilan',
  // Japanese
  'ai','aiko','airi','akane','akari','aki','akiko','akira','ami','aoi','asuka','atsuko',
  'aya','ayaka','ayako','ayame','ayano','ayumi','chie','chieko','chihiro','chika','chiyo',
  'chizuko','emi','emiko','eri','erika','etsuko','fumiko','hana','hanako','haruka',
  'harumi','hikari','hikaru','hina','hinata','hiroko','hitomi','honoka','hoshi','hotaru',
  'izumi','junko','kaede','kanako','kanon','kaori','kasumi','kazue','kazuko','kazumi',
  'keiko','kimiko','kiyoko','koharu','kokoro','kumiko','kyo','kyoko','madoka','mai',
  'maiko','maki','makiko','mami','mana','manami','mari','mariko','masako','michi',
  'michiko','midori','miho','mika','miki','minako','minami','misaki','mitsuko','miwa',
  'miyako','miyu','miyuki','mizuki','moe','momoko','nana','nanako','nanami','nao',
  'naoko','naomi','natsuki','natsumi','nodoka','noriko','otoha','rei','reiko','ren',
  'rena','rie','rika','riko','rin','rina','rio','risa','rui','rumi','ryoko','sachiko',
  'saki','sakura','sanae','satsuki','sayaka','sayuri','seiko','shizuka','shizuko',
  'suzume','takako','tamaki','tamiko','teruko','tomiko','tomoko','tomomi','tsubaki',
  'tsukiko','wakana','yasu','yasuko','yoko','yori','yoshiko','yua','yui','yuika','yuki',
  'yukiko','yuko','yumi','yumiko','yuna','yuri','yuriko','yuuna',
  // Korean
  'areum','bora','chaewon','dahyun','eunbi','eunha','eunji','eunmi','eunso','eunyoung',
  'gayoung','haeun','hana','hayoung','heejin','hyejin','hyemin','hyerin','hyojin',
  'hyorin','iseul','jieun','jimin','jina','jisoo','jiwon','jiyeon','jiyoung','mikyung',
  'mina','minji','minjoo','minseo','minyoung','naeun','nari','saerom','seohyun',
  'seoyeon','seulgi','somin','sooyeon','sooyoung','soyeon','sujin','sumin','sunhee',
  'yejin','yerim','yewon','yoojin','yoona','yoonah','yuna','yunji',

  // --- Middle Eastern / Arabic ---
  'aaliyah','abeer','afaf','ahlam','aida','aisha','alia','aliya','amal','amani','amina',
  'amira','anan','arwa','asma','aziza','badria','basma','bilqis','bushra','dalia','dalila',
  'dina','duaa','eman','fadila','fadwa','faiza','farida','fatima','fawzia','ghada',
  'habiba','haifa','hajar','hakima','hala','halima','hamida','hanan','haneen','haniya',
  'hayat','hiba','huda','huriya','husna','iman','inaam','intissar','isra','itidal',
  'jamila','jinan','karima','khadija','khayriya','kulthum','laila','lamia','lamya','lana',
  'latifa','layla','leena','leila','lina','lubna','lujayn','lujain','maha','maisa',
  'majida','malak','maram','mariam','marwa','maryam','maysa','maysoon','mona','muna',
  'munira','nabila','nada','nadia','nadira','nagla','naima','najat','najla','najwa',
  'nariman','nasreen','nawal','nayla','nazli','nesma','nida','nihad','nima','nisreen',
  'noha','noor','noura','nura','ola','omnia','rabab','rabi','rafa','raghad','rahaf',
  'rahma','raja','rajaa','rana','randa','rania','raniya','rasha','rawda','raya','reem',
  'reham','rima','ruba','ruqaya','ruqayya','saadia','sabiha','safa','safiya','sahar',
  'sahira','saida','sakina','salima','salma','salwa','sama','samar','samia','samira',
  'sana','sanaa','sawsan','shahd','shaima','shaimaa','siham','sireen','souad','suha',
  'suhaila','sumaya','sundus','tahani','tamara','thanaa','wafa','wafaa','warda','widad',
  'wisam','yara','yasmin','yusra','zahra','zainab','zakiya','zara','zarifa','zeinab',
  'zineb','zubaida',
  // Turkish
  'aylin','aysegul','aysel','aysenur','aysu','bahar','belgin','berna','betul','burcu',
  'busra','canan','cansu','cemre','defne','derya','didem','dilek','ebru','ece','elif',
  'emine','esra','filiz','gamze','gizem','gonca','gulcan','gulden','guler','gulnur',
  'gulsen','handan','hatice','hilal','hulya','idil','ilknur','ipek','irem','lale',
  'leman','leyla','melek','meltem','merve','meryem','nalan','naz','nazli','neslihan',
  'nesrin','nihal','nilufer','nuray','nurcan','nurhan','ozge','ozlem','pelin','pinar',
  'rabia','reyhan','saadet','seher','selin','selma','semra','sena','serap','sevgi',
  'sevil','sibel','simge','sinem','songul','su','sule','sultan','tuba','tugba',
  'tugce','turkan','ulku','yagmur','yasemin','yeliz','yesim','zehra','zeynep','zumra',
  // Persian
  'afsaneh','anahita','azadeh','bahar','darya','delara','dina','elnaz','elham','farah',
  'farnaz','farnoush','fatemeh','fereshteh','ghazal','goli','golnaz','homa','jaleh',
  'kimiya','ladan','laleh','mahsa','mahshid','mahtab','mana','maryam','mina','minoo',
  'mitra','mojgan','nargis','nasrin','nastaran','neda','negah','niloufar','nooshin',
  'parisa','parnian','pegah','raha','roshanak','roxana','sahar','sara','setareh','shabnam',
  'shaghayegh','shahla','shirin','shohreh','shiva','sima','sogol','solmaz','soraya',
  'taraneh','tarannom','yasaman','zahra','ziba',

  // --- African ---
  'abena','abimbola','adaeze','adanna','adaobi','adaora','adwoa','afua','aisha','akosua',
  'amahle','amara','aminata','anele','ayo','ayodele','binta','blessing','busayo',
  'chiamaka','chidinma','chika','chimamanda','chioma','chisom','damilola','efua',
  'enobong','eniola','eseohe','fadilah','fatou','favour','fola','folake','folasade',
  'funke','gift','hadiza','halima','ifeanyi','ife','ifeoma','imani','ines','isioma',
  'jumoke','kemi','keturah','khadijah','lindiwe','makena','mariam','modupe','morayo',
  'nala','nalini','ndidi','ngozi','nneka','nneoma','nwando','obiageli','oluwatoyin',
  'omolara','omoye','onyinye','precious','promise','simisola','siphokazi','temitope',
  'thandiwe','titilayo','tochi','tolulope','uchenna','ujunwa','wanjiku','yewande','zainab',
  'zuri',

  // --- Filipino ---
  'aileen','alma','amihan','avelina','belen','carmela','corazon','cristina','dalisay',
  'edna','estrella','felicidad','filipina','gracia','imelda','josefa','ligaya','lorna',
  'lualhati','luwalhati','luz','malaya','maricris','maricel','marites','mayumi','melinda',
  'milagros','mutya','nelia','nena','paraluman','perla','rosario','socorro','soledad',
  'tala','teresita','visitacion',

  // --- Hawaiian / Pacific Islander ---
  'ailani','aloha','haunani','haukea','ilima','iolana','kaia','kaila','kalani','kalei',
  'kanani','kapua','keala','keilani','kiana','lani','leilani','mahina','malia','maile',
  'moana','nalani','noelani',
]);
const MALE_NAMES = new Set([
  // --- English / American ---
  'aaron','abel','abraham','adam','addison','adrian','aidan','aiden','alan','albert',
  'alec','alejandro','alex','alexander','alexis','alfred','ali','allen','alton','alvin',
  'ambrose','amos','andre','andrew','andy','angel','angus','anthony','antonio','archer',
  'archie','arlo','armando','arnold','art','arthur','asher','ashton','atlas','august',
  'augustine','austin','avery','axel',
  'bailey','barnaby','barrett','barry','bartholomew','basil','beau','beckett','ben',
  'benedict','benjamin','bennett','benson','bernard','bert','billy','bishop','blade',
  'blaine','blair','blake','bobby','bodhi','boris','boston','bowen','brad','bradford',
  'bradley','brady','brandon','brant','braxton','brayden','brendan','brennan','brent',
  'brett','brian','briar','bridger','brock','broderick','brody','brooks','bruce','bruno',
  'bryan','bryant','bryce','bryson','buck','burt','burton','byron',
  'cade','caden','caleb','callum','calvin','cameron','campbell','carey','carl','carlos',
  'carlton','carter','casey','cason','cassius','cedar','cecil','cedric','chad','chance',
  'chandler','charles','charlie','chase','chester','chris','christian','christopher',
  'clarence','clark','claude','clay','clayton','clement','cleveland','cliff','clifford',
  'clifton','clint','clinton','clive','clyde','coby','cody','colby','cole','coleman',
  'colin','collin','colton','connor','conrad','cooper','corbin','cordell','corey','cory',
  'craig','cristian','crosby','cruz','cullen','curt','curtis','cyrus',
  'dakota','dale','dallas','dalton','damian','damien','damon','dan','dane','daniel',
  'danny','dante','darius','darnell','darrell','darren','darryl','darwin','dave','david',
  'davis','dawson','deacon','dean','deandre','declan','demetrius','denis','dennis','denver',
  'derek','derrick','desmond','devin','devon','dewayne','dexter','diego','dillon','dirk',
  'dominic','dominick','don','donald','donnie','donovan','dorian','doug','douglas','drake',
  'drew','duane','duncan','dustin','dwight','dylan',
  'earl','easton','eddie','edgar','edison','edmund','eduardo','edward','edwin','eli',
  'elias','elijah','elliot','elliott','ellis','elmer','elton','elvis','emanuel','emerson',
  'emilio','emmanuel','emmett','enrique','eric','erik','ernest','ernesto','ervin','erwin',
  'ethan','eugene','evan','everett','ezekiel','ezra',
  'fabian','felix','fernando','finley','finn','fisher','fletcher','floyd','flynn','ford',
  'forest','forrest','foster','francis','francisco','frank','frankie','franklin','fred',
  'freddie','frederick','fritz',
  'gabe','gabriel','gage','gale','gareth','garland','garrett','garrison','gary','gavin',
  'gene','geoffrey','george','gerald','geraldo','gerard','gerardo','gideon','gilbert',
  'giles','glen','glenn','gordon','grady','graham','grant','grayson','greg','gregory',
  'greyson','griffin','grover','guillermo','gunnar','gunner','gus','gustavo','guy',
  'hale','hamilton','hank','hans','harlan','harley','harold','harris','harrison','harry',
  'harvey','hasan','hawkins','hayden','hayes','heath','hector','henry','herbert','herman',
  'holden','homer','horace','houston','howard','hudson','huey','hugh','hugo','humphrey',
  'hunter',
  'ian','ibrahim','ignacio','ike','ira','irving','irwin','isaac','isaiah','ishmael',
  'ismael','israel','ivan','ivor',
  'jace','jack','jackson','jacob','jaden','jake','jamal','james','jameson','jamie',
  'jared','jarrett','jarvis','jason','jasper','javier','jay','jayden','jaylen','jayson',
  'jeff','jefferson','jeffery','jeffrey','jensen','jeremiah','jeremy','jermaine','jerome',
  'jerry','jesse','jesus','jett','jim','jimmy','joaquin','jody','joe','joel','joey','john',
  'johnathan','johnny','jon','jonah','jonas','jonathan','jordan','jorge','jose','joseph',
  'josh','joshua','josiah','jude','julian','julio','julius','junior','justin',
  'kai','kaleb','kameron','kane','karl','karson','keaton','keegan','keith','kellan','kelly',
  'kelvin','ken','kendall','kendrick','kenneth','kenny','kent','kerry','kevin','khalil',
  'kieran','killian','king','kingsley','kirk','knox','kolby','kurt','kurtis','kyle',
  'lamar','lance','landon','lane','larry','lars','lawrence','lawson','leandro','lee','leo',
  'leon','leonard','leonardo','leroy','lester','levi','lewis','liam','lincoln','lionel',
  'lloyd','logan','lonnie','lorenzo','louis','luca','lucas','lucian','luis','luke','luther',
  'lyle','lyndon',
  'mack','magnus','malcolm','malik','manuel','marc','marcel','marco','marcos','marcus',
  'mario','mark','marlon','marquis','marshall','martin','marvin','mason','mathew','matt',
  'matthew','matthias','maurice','maverick','max','maximilian','maxwell','melvin','merle',
  'micah','michael','miguel','mike','milan','miles','miller','milo','milton','mitchell',
  'mohammed','monroe','montgomery','morgan','morris','moses','muhammad','murray','myles',
  'nash','nate','nathan','nathaniel','neal','ned','neil','nelson','neville','nicholas',
  'nick','nicolas','nigel','noah','noel','nolan','norbert','norman',
  'oakley','oliver','omar','orlando','orson','oscar','otis','otto','owen',
  'pablo','parker','patrick','paul','paxton','pedro','percy','perry','pete','peter',
  'peyton','phil','philip','phillip','phoenix','pierce','porter','preston','prince',
  'quentin','quincy','quinn','quinton',
  'rafael','ralph','ramiro','ramon','randall','randolph','randy','raphael','rashad',
  'raul','ray','raymond','reece','reed','reese','reginald','reid','remington','rene',
  'reuben','rex','reynaldo','rhett','ricardo','richard','rick','ricky','rider','riley',
  'river','rob','robert','roberto','robin','rocco','roderick','rodney','rodrigo','roger',
  'roland','roman','romeo','ron','ronald','ronnie','roosevelt','rory','ross','rowan','roy',
  'royce','ruben','rudy','rufus','russ','russell','rusty','ryan','ryder','ryker','rylan',
  'sam','salvador','salvatore','samson','samuel','santiago','santos','saul','sawyer',
  'scott','sean','sebastian','sergio','seth','shane','shaun','shawn','sheldon','shepherd',
  'sherman','sherwin','sid','sidney','silas','simon','skyler','solomon','sonny','spencer',
  'stanley','stefan','stephan','stephen','sterling','steve','steven','stewart','stuart',
  'sullivan','sutton',
  'tanner','tate','taylor','ted','teddy','terrance','terrence','terry','thaddeus',
  'theodore','thomas','tim','timothy','titus','tobias','toby','todd','tom','tommy',
  'tony','trace','travis','trent','trenton','trevor','trey','tristan','troy','tucker',
  'turner','tyler','tyrone','tyson',
  'ulysses',
  'valentino','vance','vaughn','vernon','victor','vince','vincent','virgil',
  'wade','walker','wallace','walter','ward','warner','warren','watson','wayne','wells',
  'wendell','wesley','weston','wilbur','wilder','will','william','willie','wilson',
  'winston','wolf','woodrow','wyatt',
  'xander','xavier',
  'yahir','yusuf',
  'zachary','zack','zane','zavier','zion',

  // --- Spanish / Latin American ---
  'abelardo','adalberto','adolfo','agustin','alberto','aldo','alejo','alfonso','alfredo',
  'alonso','alvaro','amado','andres','angel','anibal','anselmo','armando','arnaldo',
  'arnulfo','arturo','augusto','aurelio','baltazar','bartolome','benicio','benito',
  'bernardo','blas','camilo','cayetano','cesar','cipriano','claudio','clemente',
  'cristobal','dario','diego','domingo','edmundo','efrain','eliseo','emiliano','emilio',
  'ernesto','esteban','eugenio','fabian','facundo','federico','felipe','fermin',
  'fernando','fidel','flavio','florencio','francisco','frederico','gabriel','gerardo',
  'german','gilberto','gonzalo','gregorio','guadalupe','guillermo','gustavo','hector',
  'heriberto','hernan','hilario','horacio','hugo','humberto','ignacio','ildefonso',
  'isidro','israel','ivan','jacinto','jacobo','jaime','javier','jeronimo','jesus',
  'joaquin','jorge','jose','josue','juan','julian','julio','lazaro','leandro','leonardo',
  'leopoldo','lino','lorenzo','lucas','luciano','luis','manuel','marcelo','marcos',
  'mariano','mario','martin','mateo','matias','mauricio','maximo','miguel','moises',
  'narciso','nestor','nicolas','norberto','octavio','omar','orlando','oscar','osvaldo',
  'pablo','pancho','pascual','patricio','pedro','rafael','raimundo','ramiro','ramon',
  'raul','reinaldo','renato','ricardo','rigoberto','roberto','rodolfo','rodrigo',
  'rogelio','rolando','roman','roque','rosario','ruben','ruperto','salvador','santiago',
  'santos','sebastian','sergio','silvio','simon','teodoro','tomas','trinidad','ulises',
  'valentin','vicente','victor','virgilio','xavier',

  // --- French ---
  'adrien','alain','alexandre','alexis','alphonse','amaury','anatole','andre','anselme',
  'antoine','armand','arnaud','aurelien','baptiste','basile','bastien','benoit',
  'bernard','blaise','boris','brice','bruno','cedric','charles','christophe','claude',
  'clement','corentin','cyprien','damien','denis','didier','dimitri','dominique','edmond',
  'edouard','emile','emmanuel','eric','ernest','etienne','eugene','fabien','fabrice',
  'fernand','florent','florian','francis','franck','francois','frederic','gabriel',
  'gaetan','gaspard','gaston','gautier','gerard','germain','ghislain','gilles','gregoire',
  'guillaume','gustave','guy','hadrien','henri','herve','hubert','hugues','jacques',
  'jean','jerome','joel','joseph','julien','laurent','leon','lionel','loic','louis','luc',
  'lucas','lucien','ludovic','marc','marcel','mathias','mathieu','matthieu','maurice',
  'maxime','michel','nicolas','noel','norbert','olivier','pascal','patrice','paul',
  'philippe','pierre','quentin','raphael','raymond','regis','remi','renard','renaud',
  'rene','richard','robert','roch','rodolphe','roger','roland','romain','samuel',
  'sebastien','serge','simon','stephane','sylvain','thibault','thibaut','thierry',
  'thomas','timothee','tristan','valentin','victor','vincent','virgile','vivien','xavier',
  'yann','yves',

  // --- Italian ---
  'adriano','agostino','alberto','aldo','alessio','alfonso','alfredo','amedeo','andrea',
  'angelo','antonello','antonio','attilio','augusto','aurelio','bartolomeo','benedetto',
  'beniamino','benito','bernardo','bruno','carlo','carmelo','cesare','claudio','corrado',
  'cosimo','cristiano','dario','davide','dino','domenico','donato','edoardo','emanuele',
  'emiliano','emilio','enrico','enzo','ermanno','ernesto','ettore','eugenio','fabio',
  'fabrizio','federico','felice','ferdinando','filippo','flavio','francesco','franco',
  'gabriele','gaetano','giacomo','giancarlo','gianfranco','gianluca','gianluigi',
  'gianmarco','gianni','gino','giorgio','giovanni','giuliano','giulio','giuseppe',
  'gregorio','guglielmo','guido','ignazio','jacopo','lauro','lazzaro','leonardo','lorenzo',
  'luca','luciano','lucio','luigi','marcello','marco','mario','massimiliano','massimo',
  'matteo','mattia','maurizio','mauro','michele','mirco','nicola','niccolo','nunzio',
  'orazio','orlando','ottavio','paolo','pasquale','patrizio','piero','pietro','raffaele',
  'raimondo','renato','renzo','riccardo','rinaldo','roberto','rocco','rodolfo','romano',
  'romeo','rosario','ruggero','salvatore','sandro','sergio','silvano','silvio','simone',
  'stefano','tiziano','tommaso','ubaldo','ugo','umberto','valentino','valerio','vincenzo',
  'virgilio','vito','vittorio',

  // --- German / Scandinavian ---
  'achim','adalbert','adolf','aksel','albrecht','aldric','alf','anders','andreas','anton',
  'arne','arno','arvid','august','axel','baldur','benedikt','bengt','bernd','bernhard',
  'birger','bjorn','bo','boris','burkhard','carl','carsten','christian','christoph',
  'claus','dag','detlef','dieter','dietrich','dirk','eberhard','eckhard','edgar','edvard',
  'egon','einar','ekkehard','elias','emil','erik','ernst','erwin','eugen','fabian',
  'falk','felix','ferdinand','florian','folkert','franz','frederic','frederik','friedhelm',
  'friedrich','fritz','gerd','gerhard','gerolf','gottfried','gregor','gunnar','gunter',
  'gunther','gustav','hakon','hakan','hannes','hanno','hans','harald','hartmut','hauke',
  'heinrich','helmut','hendrik','henning','henrik','herbert','hermann','horst','hubertus',
  'hugo','ingo','ingvar','ivar','jakob','jan','jens','joakim','joachim','johan','johann',
  'johannes','jonas','jorgen','jorg','juergen','jurgen','kai','karl','karsten','kaspar',
  'kilian','kjell','klaus','knut','konrad','kristian','kurt','lars','lasse','leif',
  'lennart','lorenz','lothar','ludwig','lukas','magnus','manfred','markus','martin',
  'mathias','matthias','max','maximilian','morten','niels','niklas','nils','norbert',
  'olaf','oliver','oskar','otto','paul','peter','philipp','rainer','ralf','rasmus',
  'reinhard','reinhold','rolf','rudi','rudiger','rudolf','rupert','sascha','sebastian',
  'siegfried','sigmund','sigurd','soren','stefan','steffen','stig','sven','theo','theodor',
  'thomas','thorsten','tillman','tobias','torben','torsten','udo','ulf','ulrich','uwe',
  'valentin','viktor','volker','waldemar','walter','werner','wilhelm','willi','winfried',
  'wolf','wolfgang',

  // --- Eastern European / Slavic ---
  'adam','aleksandar','aleksander','aleksei','aleksy','alexandr','andrei','andrej','andrzej',
  'anton','arkadiusz','artem','artur','bartosz','bodan','bogdan','bohumil','bojan','boris',
  'borislav','branimir','branislav','bronislaw','czeslaw','damir','dariusz','davorin',
  'dimitar','dmitri','dmitriy','dmitry','dragan','dragomir','dusan','egor','fedor',
  'filip','fyodor','gavril','gennady','georgi','goran','grzegorz','henryk','igor','ilya',
  'ivan','ivo','jacek','jan','janusz','jarek','jaroslaw','jaroslav','jerzy','jiri',
  'josef','jozef','juraj','kamil','karol','kazimierz','kirill','konstantin','krzysztof',
  'lech','leszek','lev','ljubo','ljubomir','luka','lukas','lukasz','marek','marian',
  'marius','martin','matej','mateusz','michal','milan','milos','miloslav','mirko',
  'miroslav','mladen','nikita','nikola','nikolai','nikolay','oleg','ondrej','patrik',
  'pavel','pawel','petar','petr','piotr','predrag','przemyslaw','radek','radim','radomir',
  'radoslav','rafal','roman','rostislav','ruslan','ryszard','sasha','sergei','sergey',
  'sinisa','slavko','slobodan','stanislaw','stanislav','stefan','stepan','szymon','tadeas',
  'tadeusz','tibor','todor','tomas','tomasz','vaclav','vadim','valentin','vasil','vasily',
  'veniamin','viktor','vitaliy','vitaly','vlad','vladilen','vladimir','vladislav',
  'vlastimil','vojtech','vsevolod','witold','wlodzimierz','wojciech','yakov','yaroslav',
  'yevgeny','yuri','zbigniew','zdenek','zdenko','zeljko','zoltan','zoran',

  // --- South Asian ---
  'aarav','abhay','abhi','abhijit','abhilash','abhimanyu','abhishek','aditya','ajay',
  'ajit','akash','akhil','akshar','alok','amar','ameet','amit','amitabh','amol','anand',
  'aniket','anil','anish','anjay','ankit','ankur','anoop','ansh','anuj','aravind','arjun',
  'arun','aryan','ashish','ashok','ashwin','atul','balaji','bala','bharat','bikram',
  'chandan','chirag','darshan','deepak','dev','devendra','dhruv','dilip','dinesh','dipak',
  'gaurav','gautam','girish','gopal','govind','hari','harish','harsh','hemant','hitesh',
  'indra','ishaan','jagdish','jai','jatin','jay','jayesh','kailash','kamal','karan',
  'karthik','kishore','krishna','kumar','kunal','lakshman','lalit','lokesh','madhav',
  'mahesh','manas','manish','manoj','mayank','mihir','milan','mohit','mohan','mukesh',
  'nandan','naresh','narendra','naveen','neeraj','nikhil','nilesh','niraj','nishant',
  'nitesh','nitin','om','pankaj','paras','parth','pavan','piyush','prabhu','pradeep',
  'prakash','pranav','prasad','prashant','pratik','pravin','puneet','raghav','rahul',
  'raj','rajat','rajeev','rajendra','rajesh','rajiv','rakesh','ram','ramesh','ranjit',
  'ratan','ravi','ravindra','ritesh','rohit','roshan','sachin','sagar','sahil','sameer',
  'sandeep','sanjay','sanjit','sankar','santosh','sarang','satish','shailesh','shankar',
  'sharad','shashi','shekhar','shivam','shreyas','shyam','siddharth','sudhir','suhas',
  'sujay','sujith','sukant','sumit','sunil','suraj','suresh','surya','sushil','tarun',
  'tushar','uday','ujjwal','umesh','varun','venkat','vijay','vikas','vikram','vinay',
  'vinod','vipin','vishal','vishnu','vivek','yash','yogesh',
  // Pakistani / Bangladeshi
  'abdur','adnan','afzal','ahad','ahmed','akhtar','akram','altaf','amin','amir','anwar',
  'arif','asad','asif','atif','azhar','babar','bilal','danish','ehsan','ejaz','fahad',
  'fahim','faraz','farhan','farid','faisal','farooq','habib','haider','hamid','hammad',
  'hamza','haris','hasan','hashim','hassan','imran','irfan','ishaq','junaid','kamran',
  'kashif','khalid','khurram','liaqat','majid','mansoor','masood','moin','mujtaba',
  'murad','mustafa','nadeem','naeem','nasir','naveed','nazir','noman','omair','owais',
  'pervaiz','qadir','qasim','rafiq','rashid','raza','rizwan','saad','sabir','sadiq',
  'saeed','sajid','saleem','salman','samir','shafiq','shahid','shakil','sharif','shoaib',
  'sohail','sultan','tahir','tanveer','tariq','umar','usman','waheed','waqar','waseem',
  'yousuf','zafar','zahid','zaheer','zain','zakir','zia','zubair',

  // --- East Asian ---
  // Chinese (romanized)
  'bao','bo','chang','chao','chen','cheng','chi','chun','da','dong','fan','fei','feng',
  'fu','gang','guang','guo','hai','hao','he','hong','hu','hua','huang','hui','jia',
  'jian','jiang','jie','jin','jing','jun','kai','kang','lei','li','liang','lin','long',
  'ming','nan','peng','qi','qiang','qin','rui','sheng','shi','shu','tao','wei','wen',
  'xiang','xin','xing','xiong','xu','xuan','yan','yang','yi','yong','yu','yuan','yue',
  'yun','zhe','zhen','zheng','zhi','zhong','zhou',
  // Japanese
  'akihiro','akio','akira','arata','atsushi','daichi','daigo','daiki','daisuke','eiji',
  'fumio','genji','goro','hajime','haru','haruki','haruo','haruto','hayato','hideaki',
  'hideki','hideto','hideo','hikaru','hinata','hiraku','hiro','hiroaki','hirofumi',
  'hiroki','hiromasa','hironori','hiroshi','hiroto','hiroyuki','hisao','hisashi','ichiro',
  'isamu','itsuki','jiro','jun','junichi','junpei','kaede','kaito','kakeru','kaoru',
  'kazuhiko','kazuhiro','kazuki','kazuma','kazuo','kazuya','keiji','ken','kenichi','kenji',
  'kensuke','kenta','kenzo','kohei','koichi','koji','kosuke','kouki','kousuke','kunio',
  'makoto','mamoru','manabu','masaaki','masahiko','masahiro','masaki','masami','masao',
  'masaru','masashi','masato','masayuki','minoru','mitsuo','mitsuru','naoki','naoto',
  'noboru','nobuo','nobuyuki','nori','norio','osamu','reiji','ren','riku','ryo','ryoichi',
  'ryosuke','ryota','ryuichi','ryuji','saburo','satoru','satoshi','seiichi','shinji',
  'shinsuke','shinya','shiro','sho','shota','shou','shuichi','shuji','shun','shunta',
  'shunsuke','sosuke','sota','subaru','susumu','tadashi','taichi','taiga','taiki','takahiro',
  'takashi','takayuki','takeo','takeru','takeshi','takumi','takuya','taro','tatsuo',
  'tatsuya','teruo','tetsuya','tomohiro','tomoya','toru','toshiaki','toshiki','toshio',
  'tsubasa','tsukasa','tsutomu','tsuyoshi','yamato','yasuhiro','yasuo','yasushi','yoichi',
  'yoshiaki','yoshihiro','yoshiki','yoshio','yosuke','yota','yuichi','yuji','yuki',
  'yukio','yuma','yusaku','yusei','yusuke','yuta','yuto','yuuki',
  // Korean
  'beomseok','byungho','changmin','chanyeol','cheol','daehyun','donghyun','dongwoo',
  'eunwoo','gunho','gyumin','haejin','hansol','hyojin','hyunsoo','ilhoon','inhwan',
  'jaehyun','jaemin','jaewon','jeonghoon','jihoon','jimin','jinseok','jinyoung','jonghyun',
  'joonho','jooyoung','junghwan','jungkook','junhyeok','junwoo','kihyun','kyungsoo',
  'minjun','minseok','minsoo','namjoon','sanghoon','sehun','seojun','seokjin','seongmin',
  'seungho','seunghyun','seungmin','sihyun','siwoo','sungho','sungjin','taehyung','woojin',
  'wooseok','yeojin','yonghwa','yoongi','youngjae','yunho',

  // --- Middle Eastern / Arabic ---
  'abbas','abd','abdallah','abdel','abdelaziz','abdelrahman','abdi','abdullah','adel',
  'adham','adil','adnan','ahmad','ahmed','akbar','akram','ali','amin','amir','ammar',
  'anwar','ashraf','aws','ayman','aziz','badr','bahir','bakr','bashar','bashir','basim',
  'bilal','burhan','daud','essam','eyas','eyad','fadel','fahd','faisal','farid','faris',
  'farouq','fawzi','firas','fouad','ghassan','habib','hadi','hafez','haider','hakim',
  'halim','hamad','hamed','hamid','hamza','hani','haris','harun','hasan','hashim',
  'hassan','hatim','hazem','hesham','hisham','hussain','hussein','ibrahim','idris','ihab',
  'ihsan','imad','isa','ismail','issam','jaafar','jabir','jalal','jalil','jamal','jamil',
  'jawad','kamal','kardal','kareem','karim','kazem','khalid','khalil','khayyam','labib',
  'latif','laith','mahdi','mahmoud','majed','majid','malik','mamoun','mansour','marwan',
  'masoud','mazin','mehdi','moaz','mohammed','mohannad','muhannad','moustafa','muaz',
  'mubarak','mudassir','muhammad','mukhtar','munir','musa','musab','mustafa','mutasim',
  'nabil','nader','nadir','naji','nasim','nasser','nasr','nazir','nizar','nour','numan',
  'obaid','omar','osama','othman','qais','qasem','qasim','rabih','radi','rafiq','ragheb',
  'rahim','raja','ramadan','rami','rasheed','rashid','ratib','rauf','rayyan','riad',
  'ridwan','riyad','rushdi','saad','sabri','sadiq','saeed','safwan','sahir','said','saif',
  'sajid','salah','saleem','salem','salim','salman','samir','sami','saud','shadi','shafiq',
  'shakir','sharif','suhail','sulaiman','sultan','taha','taher','talal','tamim','tarek',
  'tariq','tawfiq','thabet','usama','uthmaan','wahid','waleed','walid','waseem','yaser',
  'yasin','yassir','youssef','yousuf','yusuf','zaid','zayd','ziad','ziyad',
  // Turkish
  'ahmet','alp','arda','atakan','aybars','baran','baris','berk','berke','berkay','burak',
  'cem','cengiz','cihan','cuneyt','dogan','efe','emre','ender','engin','ercan','erdem',
  'erdogan','erhan','erkan','erol','faruk','fikret','firat','gokhan','gokmen','guney',
  'gurkan','hakan','halil','haluk','hamit','hasan','husnu','huseyin','ilhan','ilker',
  'irfan','ismail','kaan','kadir','kemal','kenan','koray','levent','mehmet','mert',
  'mesut','metin','murat','mustafa','necati','nuri','oguz','onur','osman','ozgur',
  'polat','recep','ridvan','selim','serdar','serhan','serkan','sinan','suleyman','tarik',
  'tolga','tugrul','tuncay','turgut','ufuk','ugur','umit','volkan','yasin','yavuz',
  'yigit','yunus','yusuf',
  // Persian
  'abtin','afshin','ali','amir','arash','ardeshir','aria','arman','armin','arya','ashkan',
  'babak','bahman','bahram','behnam','behrad','behrouz','bijan','bizhan','cyrus','dara',
  'dariush','ebrahim','ehsan','esfandiar','farbod','farhad','farshad','farshid','farzad',
  'fereidoun','hamid','hossein','iman','iraj','jamshid','javad','kamran','kaveh','kayvan',
  'kian','kiarash','kourosh','majid','maziar','mehdi','mehran','mehrdad','mohammad',
  'mohsen','morteza','nader','navid','nima','omid','parham','parviz','payam','pedram',
  'pouya','ramin','reza','roham','rostam','sadegh','saeed','saman','samir','sepehr',
  'shahram','shahin','shahrokh','siamak','sina','sirous','sohrab','sorush','yashar',

  // --- African ---
  'abayomi','abdi','abdoulaye','abubakar','adebayo','adewale','adisa','akeem','akin',
  'amadi','amadu','ayobami','azikiwe','babajide','babatunde','baraka','bayo','chidi',
  'chike','chikezie','chinedu','chinua','chukwuemeka','chukwuma','dada','dakarai',
  'emeka','ezenwa','femi','fisayo','gbenga','idrissa','ikechukwu','jabari','jelani',
  'jibril','kehinde','kelechi','koffi','kofi','kwabena','kwaku','kwame','kwesi','lekan',
  'mandla','musa','nana','ngozi','nnamdi','nnaemeka','obafemi','obi','obiora','odion',
  'okechukwu','olalekan','olamide','olawale','olusegun','oluwafemi','oluwaseun',
  'oluwaseyi','oluwatobi','sekou','seun','sibusiso','simba','sipho','taiwo','temba',
  'tendai','thabo','tunde','uchenna','uzoma','yaw','yemi','yusuf','zuberi',

  // --- Filipino ---
  'alejandro','amado','amando','andres','angel','antonio','bayani','benito','carlos',
  'crisanto','dagohoy','dante','datu','edilberto','efren','emilio','enrique','ernesto',
  'esteban','fernando','florante','gabriel','gerardo','gregorio','herminio','isagani',
  'jose','juan','lapu','lito','lorenzo','macario','manny','marcelo','mariano','noel',
  'orlando','paciano','rafael','ramon','renato','reynaldo','ricardo','rizal','rodrigo',
  'romeo','salvador','santiago','teodoro','vicente',

  // --- Hawaiian / Pacific Islander ---
  'ailani','akamu','ekolu','ikaika','ionakana','kahale','kahoku','kai','kalani','kalei',
  'kamea','kanoa','kawai','keahi','keanu','keola','koa','konane','liko','lokahi','makoa',
  'malu','mana','nainoa','nalu','noelani',
]);
function guessGender(name) {
  const key = name.trim().split(/\s+/)[0].toLowerCase();
  if (!key) return null;
  if (FEMALE_NAMES.has(key)) return 'F';
  if (MALE_NAMES.has(key)) return 'M';
  return null;
}
// --- Debounce helper ---
let _debounceTimers = {};
function debounce(key, fn, delay) {
  clearTimeout(_debounceTimers[key]);
  _debounceTimers[key] = setTimeout(fn, delay);
}
function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
const AMERICAN_FEMALE = [
  'abby','abigail','addie','alice','allison','amanda','amber','amy','andrea','angela',
  'ann','anna','annie','ashley','audrey','barbara','becky','beth','betty','bonnie',
  'brenda','brittany','brooke','caitlin','carol','caroline','carolyn','casey','catherine',
  'charlotte','chelsea','cheryl','christina','christine','cindy','claire','colleen',
  'courtney','crystal','cynthia','dana','danielle','dawn','debbie','deborah','denise',
  'diana','diane','donna','dorothy','eileen','elaine','elizabeth','ellen','emily','emma',
  'erica','erin','evelyn','faith','faye','fran','gail','grace','gwen','hailey','hannah',
  'heather','heidi','helen','holly','jackie','jane','janet','janice','jean','jenna',
  'jennifer','jenny','jessica','jill','joan','joanne','jodi','jordan','joyce','judy',
  'julia','julie','karen','kate','katherine','kathleen','kathy','katie','kayla','kelly',
  'kim','kimberly','kristen','kristin','laura','lauren','leah','linda','lindsay','lisa',
  'liz','lori','lynn','madison','maggie','margaret','maria','marie','marilyn','marissa',
  'marlene','martha','mary','maureen','megan','melissa','michelle','molly','monica','nancy',
  'natalie','nicole','nina','olivia','pam','pamela','patricia','patty','paula','peggy',
  'penny','rachel','rebecca','renee','robin','rosa','rose','ruth','sally','samantha',
  'sandra','sara','sarah','shannon','sharon','shelley','sherry','shirley','sophia','stacy',
  'stephanie','sue','susan','tammy','tara','teresa','terry','theresa','tiffany','tina',
  'tracy','valerie','vanessa','vicki','victoria','virginia','vivian','wendy','whitney',
];
const AMERICAN_MALE = [
  'aaron','adam','alan','alex','andrew','andy','anthony','austin','barry','ben','benjamin',
  'bill','billy','blake','bob','bobby','brad','brandon','brent','brett','brian','bruce',
  'bryan','caleb','cameron','carl','chad','charles','charlie','chase','chris','christian',
  'christopher','chuck','clay','cody','colin','connor','corey','craig','curtis','dale',
  'dan','daniel','danny','darren','dave','david','dean','dennis','derek','don','donald',
  'doug','drew','dustin','dylan','ed','eddie','edward','eric','erik','ethan','evan',
  'frank','fred','garrett','gary','george','glen','gordon','grant','greg','hank','harold',
  'harry','henry','howard','hunter','jack','jackson','jacob','jake','james','jamie',
  'jason','jay','jeff','jeffrey','jeremy','jerry','jesse','jim','jimmy','joe','joel',
  'john','johnny','jon','jonathan','jordan','joseph','josh','joshua','justin','keith',
  'ken','kenneth','kenny','kevin','kyle','lance','larry','lee','leo','logan','luke',
  'marcus','mark','marshall','martin','matt','matthew','max','michael','mike','miles',
  'mitchell','nathan','neil','nick','noah','owen','pat','patrick','paul','pete','peter',
  'phil','preston','ralph','randy','ray','raymond','rich','richard','rick','rob','robert',
  'roger','ron','ross','roy','russell','ryan','sam','samuel','scott','sean','seth','shane',
  'shawn','spencer','steve','steven','stuart','ted','terry','tim','timothy','todd','tom',
  'tommy','tony','travis','trevor','troy','tyler','vince','wade','walter','warren','wayne',
  'wesley','will','william','zach','zachary',
];
function pickRandomNames(count) {
  const fList = shuffle([...AMERICAN_FEMALE]);
  const mList = shuffle([...AMERICAN_MALE]);
  const cap = s => s.charAt(0).toUpperCase() + s.slice(1);

  // Random gender split: 25%-75% female, rest male
  const minF = Math.max(2, Math.round(count * 0.25));
  const maxF = Math.min(count - 2, Math.round(count * 0.75));
  const numF = minF + Math.floor(Math.random() * (maxF - minF + 1));
  const numM = count - numF;

  const result = [];
  const usedNames = new Set();
  let fi = 0, mi = 0;

  // Add females
  for (let i = 0; i < numF; i++) {
    while (fi < fList.length && usedNames.has(fList[fi])) fi++;
    const name = fi < fList.length ? fList[fi++] : `Player ${i + 1}`;
    usedNames.add(name);
    result.push({ name: cap(name), gender: 'F' });
  }
  // Add males
  for (let i = 0; i < numM; i++) {
    while (mi < mList.length && usedNames.has(mList[mi])) mi++;
    const name = mi < mList.length ? mList[mi++] : `Player ${numF + i + 1}`;
    usedNames.add(name);
    result.push({ name: cap(name), gender: 'M' });
  }

  return shuffle(result);
}
